export interface Channel {
  id: string;
  name: string;
  logo: string;
  category: 'indonesia' | 'international';
  genre: string;
  isLive: boolean;
  currentShow: string;
  viewers: string;
  streamUrl: string;
  description: string;
  quality: 'HD' | 'FHD' | 'SD' | '4K';
  language: string;
  accentColor: string;
}

export const CHANNELS: Channel[] = [
  // ==================== INDONESIA ====================
  {
    id: 'rcti',
    name: 'RCTI',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/RCTI_logo_2019.svg/200px-RCTI_logo_2019.svg.png',
    category: 'indonesia',
    genre: 'Hiburan',
    isLive: true,
    currentShow: 'Siaran Langsung RCTI',
    viewers: '1.2M',
    streamUrl: 'https://5b63fce63df27.streamlock.net/rcti/rcti/playlist.m3u8',
    description: 'Rajawali Citra Televisi Indonesia - TV swasta pertama Indonesia',
    quality: 'HD',
    language: 'Indonesia',
    accentColor: '#E31E2D',
  },
  {
    id: 'sctv',
    name: 'SCTV',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/SCTV_logo_2017.png/200px-SCTV_logo_2017.png',
    category: 'indonesia',
    genre: 'Hiburan',
    isLive: true,
    currentShow: 'Siaran Langsung SCTV',
    viewers: '980K',
    streamUrl: 'https://5b63fce63df27.streamlock.net/sctv/sctv/playlist.m3u8',
    description: 'Surya Citra Televisi - Hiburan keluarga Indonesia',
    quality: 'HD',
    language: 'Indonesia',
    accentColor: '#FF6B00',
  },
  {
    id: 'transtv',
    name: 'Trans TV',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Trans_TV_logo.svg/200px-Trans_TV_logo.svg.png',
    category: 'indonesia',
    genre: 'Berita & Hiburan',
    isLive: true,
    currentShow: 'Siaran Langsung Trans TV',
    viewers: '750K',
    streamUrl: 'https://5b63fce63df27.streamlock.net/transtv/transtv/playlist.m3u8',
    description: 'Trans TV - Lebih Dekat di Hati',
    quality: 'HD',
    language: 'Indonesia',
    accentColor: '#E8001D',
  },
  {
    id: 'trans7',
    name: 'Trans7',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Trans7_logo_2018.svg/200px-Trans7_logo_2018.svg.png',
    category: 'indonesia',
    genre: 'Hiburan',
    isLive: true,
    currentShow: 'Siaran Langsung Trans7',
    viewers: '860K',
    streamUrl: 'https://5b63fce63df27.streamlock.net/trans7/trans7/playlist.m3u8',
    description: 'Trans7 - TV Kita Punya',
    quality: 'HD',
    language: 'Indonesia',
    accentColor: '#00A551',
  },
  {
    id: 'metrotv',
    name: 'Metro TV',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/MetroTV.svg/200px-MetroTV.svg.png',
    category: 'indonesia',
    genre: 'Berita',
    isLive: true,
    currentShow: 'Siaran Langsung Metro TV',
    viewers: '620K',
    streamUrl: 'https://5b63fce63df27.streamlock.net/metrotv/metrotv/playlist.m3u8',
    description: 'Metro TV - TV Berita Indonesia',
    quality: 'HD',
    language: 'Indonesia',
    accentColor: '#003087',
  },
  {
    id: 'tvri',
    name: 'TVRI',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/TVRI_2019.svg/200px-TVRI_2019.svg.png',
    category: 'indonesia',
    genre: 'Nasional',
    isLive: true,
    currentShow: 'Siaran Langsung TVRI',
    viewers: '430K',
    streamUrl: 'https://tvrinasional-live.akamaized.net/hls/live/2002068/tvrinasional/master.m3u8',
    description: 'TVRI - Televisi Republik Indonesia',
    quality: 'HD',
    language: 'Indonesia',
    accentColor: '#009900',
  },
  {
    id: 'kompastv',
    name: 'Kompas TV',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Kompas_TV_logo.svg/200px-Kompas_TV_logo.svg.png',
    category: 'indonesia',
    genre: 'Berita & Edukasi',
    isLive: true,
    currentShow: 'Siaran Langsung Kompas TV',
    viewers: '520K',
    streamUrl: 'https://5b63fce63df27.streamlock.net/kompastv/kompastv/playlist.m3u8',
    description: 'Kompas TV - Jernih Melihat Dunia',
    quality: 'FHD',
    language: 'Indonesia',
    accentColor: '#CC0000',
  },
  {
    id: 'nettv',
    name: 'NET.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/NET._TV_logo_2013.svg/200px-NET._TV_logo_2013.svg.png',
    category: 'indonesia',
    genre: 'Hiburan Muda',
    isLive: true,
    currentShow: 'Siaran Langsung NET.',
    viewers: '670K',
    streamUrl: 'https://5b63fce63df27.streamlock.net/nettv/nettv/playlist.m3u8',
    description: 'NET. - Televisi Masa Kini',
    quality: 'FHD',
    language: 'Indonesia',
    accentColor: '#7C3AED',
  },
  {
    id: 'gtv',
    name: 'GTV',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/GTV_2018.svg/200px-GTV_2018.svg.png',
    category: 'indonesia',
    genre: 'Hiburan',
    isLive: true,
    currentShow: 'Siaran Langsung GTV',
    viewers: '390K',
    streamUrl: 'https://5b63fce63df27.streamlock.net/gtv/gtv/playlist.m3u8',
    description: 'GTV - Global TV Indonesia',
    quality: 'HD',
    language: 'Indonesia',
    accentColor: '#FF5722',
  },
  {
    id: 'mnctv',
    name: 'MNCTV',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/MNCTV_2011_logo.svg/200px-MNCTV_2011_logo.svg.png',
    category: 'indonesia',
    genre: 'Hiburan Keluarga',
    isLive: true,
    currentShow: 'Siaran Langsung MNCTV',
    viewers: '560K',
    streamUrl: 'https://5b63fce63df27.streamlock.net/mnctv/mnctv/playlist.m3u8',
    description: 'MNCTV - Televisi Hiburan Keluarga',
    quality: 'HD',
    language: 'Indonesia',
    accentColor: '#009BD7',
  },
  {
    id: 'indosiar',
    name: 'Indosiar',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Indosiar.svg/200px-Indosiar.svg.png',
    category: 'indonesia',
    genre: 'Drama & Dangdut',
    isLive: true,
    currentShow: 'Siaran Langsung Indosiar',
    viewers: '820K',
    streamUrl: 'https://5b63fce63df27.streamlock.net/indosiar/indosiar/playlist.m3u8',
    description: 'Indosiar - Memang Untuk Anda',
    quality: 'HD',
    language: 'Indonesia',
    accentColor: '#0080FF',
  },
  {
    id: 'antv',
    name: 'ANTV',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/ANTV_logo_2016.svg/200px-ANTV_logo_2016.svg.png',
    category: 'indonesia',
    genre: 'Hiburan',
    isLive: true,
    currentShow: 'Siaran Langsung ANTV',
    viewers: '450K',
    streamUrl: 'https://5b63fce63df27.streamlock.net/antv/antv/playlist.m3u8',
    description: 'ANTV - Semua Ada di ANTV',
    quality: 'HD',
    language: 'Indonesia',
    accentColor: '#FF0033',
  },
  // ==================== INTERNATIONAL ====================
  {
    id: 'cnn',
    name: 'CNN',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/CNN.svg/200px-CNN.svg.png',
    category: 'international',
    genre: 'News',
    isLive: true,
    currentShow: 'CNN Newsroom Live',
    viewers: '3.5M',
    streamUrl: 'https://cnn-cnninternational-1-eu.akamaized.net/hls/live/2038308/cnninternational/master_3.m3u8',
    description: 'CNN International - World News Leader',
    quality: '4K',
    language: 'English',
    accentColor: '#CC0000',
  },
  {
    id: 'bbc',
    name: 'BBC World',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/BBC_Logo_2021.svg/200px-BBC_Logo_2021.svg.png',
    category: 'international',
    genre: 'News',
    isLive: true,
    currentShow: 'BBC World News',
    viewers: '2.8M',
    streamUrl: 'https://vs-hls-push-ww-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_news_channel_hd/t=3840/v=pv14/b=5070016/main.m3u8',
    description: 'BBC World News - Delivering trusted international journalism',
    quality: '4K',
    language: 'English',
    accentColor: '#BB1919',
  },
  {
    id: 'espn',
    name: 'ESPN',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/ESPN_wordmark.svg/200px-ESPN_wordmark.svg.png',
    category: 'international',
    genre: 'Sports',
    isLive: true,
    currentShow: 'SportsCenter',
    viewers: '4.2M',
    streamUrl: 'https://dai2.xumo.com/amagi_hls_data_xumo1212A-redzonelive/CDN/playlist.m3u8',
    description: 'ESPN - The Worldwide Leader in Sports',
    quality: 'FHD',
    language: 'English',
    accentColor: '#FF6600',
  },
  {
    id: 'discovery',
    name: 'Discovery',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Discovery_Channel_-_Logo_2019.svg/200px-Discovery_Channel_-_Logo_2019.svg.png',
    category: 'international',
    genre: 'Documentary',
    isLive: true,
    currentShow: 'World Discovery',
    viewers: '1.6M',
    streamUrl: 'https://dai2.xumo.com/amagi_hls_data_xumo1212A-discoveryplus/CDN/playlist.m3u8',
    description: 'Discovery Channel - The world is just awesome',
    quality: 'FHD',
    language: 'English',
    accentColor: '#0066CC',
  },
  {
    id: 'natgeo',
    name: 'Nat Geo',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Natgeologo.svg/200px-Natgeologo.svg.png',
    category: 'international',
    genre: 'Documentary',
    isLive: true,
    currentShow: 'Wild Kingdom',
    viewers: '1.3M',
    streamUrl: 'https://dai2.xumo.com/amagi_hls_data_xumo1212A-natgeo/CDN/playlist.m3u8',
    description: 'National Geographic - Inspiring people to care about the planet',
    quality: 'FHD',
    language: 'English',
    accentColor: '#FFCC00',
  },
  {
    id: 'aljazeeraen',
    name: 'Al Jazeera',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Aljazeera_eng.svg/200px-Aljazeera_eng.svg.png',
    category: 'international',
    genre: 'News',
    isLive: true,
    currentShow: 'Al Jazeera Live',
    viewers: '1.8M',
    streamUrl: 'https://live-hls-web-aje.getaj.net/AJE/index.m3u8',
    description: 'Al Jazeera English - Setting the news agenda',
    quality: 'FHD',
    language: 'English',
    accentColor: '#8B0000',
  },
  {
    id: 'bloomberg',
    name: 'Bloomberg',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Bloomberg_logo.svg/200px-Bloomberg_logo.svg.png',
    category: 'international',
    genre: 'Business',
    isLive: true,
    currentShow: 'Markets Today',
    viewers: '900K',
    streamUrl: 'https://dai2.xumo.com/amagi_hls_data_xumo1212A-bloomberg/CDN/playlist.m3u8',
    description: 'Bloomberg Television - Business and finance news',
    quality: 'FHD',
    language: 'English',
    accentColor: '#2E4A62',
  },
  {
    id: 'cartoon',
    name: 'Cartoon Network',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cartoon_Network_2010_logo.svg/200px-Cartoon_Network_2010_logo.svg.png',
    category: 'international',
    genre: 'Kids',
    isLive: true,
    currentShow: 'Cartoon Network Live',
    viewers: '2.3M',
    streamUrl: 'https://dai2.xumo.com/amagi_hls_data_xumo1212A-cartoonnetwork/CDN/playlist.m3u8',
    description: 'Cartoon Network - Check it',
    quality: 'HD',
    language: 'English',
    accentColor: '#000000',
  },
  {
    id: 'euronews',
    name: 'Euronews',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Logo_Euronews.svg/200px-Logo_Euronews.svg.png',
    category: 'international',
    genre: 'News',
    isLive: true,
    currentShow: 'Euronews Live',
    viewers: '760K',
    streamUrl: 'https://euronews-euronews-mobile-1-eu.akamaized.net/hls/live/2033487/euronewsHD/index.m3u8',
    description: 'Euronews - All views. All voices.',
    quality: 'FHD',
    language: 'English',
    accentColor: '#0033CC',
  },
  {
    id: 'nhkworld',
    name: 'NHK World',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/NHK_World_logo.svg/200px-NHK_World_logo.svg.png',
    category: 'international',
    genre: 'Documentary & News',
    isLive: true,
    currentShow: 'NHK World Live',
    viewers: '540K',
    streamUrl: 'https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index_4M.m3u8',
    description: 'NHK World - Japan Broadcasting Corporation',
    quality: '4K',
    language: 'English/Japanese',
    accentColor: '#006699',
  },
  {
    id: 'cgtn',
    name: 'CGTN',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/CGTN_logo.svg/200px-CGTN_logo.svg.png',
    category: 'international',
    genre: 'News',
    isLive: true,
    currentShow: 'CGTN Live',
    viewers: '490K',
    streamUrl: 'https://livefr.cgtn.com/1000e/prog_index.m3u8',
    description: 'CGTN - China Global Television Network',
    quality: 'FHD',
    language: 'English/Chinese',
    accentColor: '#CC0000',
  },
];

export const getChannelsByCategory = (category: 'all' | 'indonesia' | 'international' | 'favorites', favorites: string[]) => {
  switch (category) {
    case 'indonesia':
      return CHANNELS.filter(c => c.category === 'indonesia');
    case 'international':
      return CHANNELS.filter(c => c.category === 'international');
    case 'favorites':
      return CHANNELS.filter(c => favorites.includes(c.id));
    default:
      return CHANNELS;
  }
};

export const getChannelById = (id: string) => CHANNELS.find(c => c.id === id);

export const getPrevChannel = (id: string): Channel | null => {
  const idx = CHANNELS.findIndex(c => c.id === id);
  if (idx <= 0) return CHANNELS[CHANNELS.length - 1];
  return CHANNELS[idx - 1];
};

export const getNextChannel = (id: string): Channel | null => {
  const idx = CHANNELS.findIndex(c => c.id === id);
  if (idx < 0 || idx >= CHANNELS.length - 1) return CHANNELS[0];
  return CHANNELS[idx + 1];
};

export const getChannelIndex = (id: string): number => CHANNELS.findIndex(c => c.id === id);
